export const helpGuideSteps = [
  {
    id: "welcome",
    eyebrow: "SELAMAT DATANG",
    title: "Kenali AksesKota dalam 2 menit",
    description: "Panduan ini memperagakan cara mencari rute, membaca data peta, dan memperbarui kondisi jalan bersama komunitas.",
    hint: "Kamu tetap dapat membuka panduan melalui tombol tanda tanya.",
    target: null,
    panel: null,
    demo: "overview",
  },
  {
    id: "search",
    eyebrow: "MENCARI RUTE · 01",
    title: "Masukkan awal dan tujuan",
    description: "Titik awal dapat memakai GPS atau nama tempat. Ketik tujuan, pilih hasil yang sesuai, lalu tekan Cari rute.",
    hint: "Contoh: Lokasi saya → Kebun Raya Bogor",
    target: "search",
    panel: null,
    demo: "search",
  },
  {
    id: "mode",
    eyebrow: "PREFERENSI · 02",
    title: "Pilih kebutuhan mobilitas",
    description: "Profil mengubah bobot penilaian. Kursi Roda mengutamakan ramp, Lansia mengutamakan tempat duduk, dan Low Vision mengutamakan guiding block.",
    hint: "Profil dapat diganti kapan saja tanpa menghapus tujuan.",
    target: "mode",
    panel: null,
    demo: "mode",
  },
  {
    id: "shade",
    eyebrow: "KENYAMANAN · 03",
    title: "Cari jalur yang lebih teduh",
    description: "Rute teduh membandingkan ruas berdasarkan observasi naungan. Jika data belum cukup, AksesKota tidak membuat nilai palsu.",
    hint: "Aktifkan sebelum menekan Cari rute.",
    target: "shade",
    panel: null,
    demo: "shade",
  },
  {
    id: "heat",
    eyebrow: "LAPISAN PETA · 04",
    title: "Lihat estimasi paparan panas",
    description: "Lapisan panas membantu membandingkan area pada jam berbeda berdasarkan cuaca, ruang hijau, dan observasi ruas.",
    hint: "Ini estimasi pendukung, bukan sensor suhu permukaan realtime.",
    target: "heat",
    panel: null,
    demo: "heat",
  },
  {
    id: "directory",
    eyebrow: "TEMPAT · 05",
    title: "Jelajahi Direktori Bogor",
    description: "Direktori berisi tempat, foto, ulasan, rating, serta bukti fasilitas seperti ramp, toilet, tempat duduk, dan parkir aksesibel.",
    hint: "Pilih tempat untuk menjadikannya tujuan perjalanan.",
    target: "directory",
    panel: null,
    demo: "directory",
  },
  {
    id: "directory-add",
    eyebrow: "KONTRIBUSI TEMPAT",
    title: "Tambahkan tempat yang belum tersedia",
    description: "Buka formulir ini untuk mengusulkan tempat baru. Nama, kategori, alamat, titik lokasi, catatan, dan foto tampak depan diperlukan.",
    hint: "Usulan belum langsung masuk direktori publik.",
    target: "directory-add-button",
    panel: "directory",
    action: "directory-list",
    demo: "directory-add",
  },
  {
    id: "directory-add-proof",
    eyebrow: "BUKTI TEMPAT",
    title: "Foto dan lokasi wajib dapat diperiksa",
    description: "Ambil foto papan nama atau tampak depan dan gunakan GPS. Data ini membantu warga lain memastikan tempat, alamat, dan titik petanya sama.",
    hint: "Mode panduan hanya membuka formulir dan tidak mengirim data.",
    target: "directory-new-place-form",
    panel: "directory",
    action: "directory-add",
    demo: "camera",
  },
  {
    id: "directory-feature-status",
    eyebrow: "STATUS FASILITAS",
    title: "Bedakan indikasi dari fakta terverifikasi",
    description: "Hijau berarti terverifikasi ada, merah terverifikasi tidak ada, oranye hanya indikasi sumber, dan abu-abu berarti belum ada bukti.",
    hint: "Data scraping tidak otomatis menjadi centang hijau.",
    target: "directory-facility-status",
    panel: "directory",
    action: "directory-open-place",
    demo: "directory-status",
  },
  {
    id: "directory-correction",
    eyebrow: "KOREKSI FASILITAS",
    title: "Laporkan fasilitas ada atau tidak ada",
    description: "Pilih ramp, lift, toilet, parkir aksesibel, guiding block, atau bebas tangga. Catat kondisi yang benar-benar terlihat dan sertakan foto.",
    hint: "Contoh: parkir tercantum di sumber, tetapi marka dan ruangnya ternyata tidak ada.",
    target: "directory-evidence-form",
    panel: "directory",
    action: "directory-open-evidence",
    demo: "directory-correction",
  },
  {
    id: "directory-consensus",
    eyebrow: "VALIDASI WARGA",
    title: "Tiga warga lain memeriksa bukti",
    description: "Pengusul tidak boleh memvalidasi sendiri. Warga lain dapat memilih Sesuai, Tidak sesuai, atau Cek ulang setelah melihat foto dan catatan.",
    hint: "Suara yang bertentangan membuat status Perlu dicek ulang.",
    target: "directory-pending-validation",
    panel: "directory",
    action: "directory-open-place",
    demo: "quorum",
  },
  {
    id: "directory-impact",
    eyebrow: "PERUBAHAN DATA",
    title: "Status publik berubah setelah konsensus",
    description: "Tiga persetujuan menerbitkan tempat baru atau memperbarui status fasilitas. Tiga penolakan menolak usulan; konflik tidak dipaksa menjadi fakta.",
    hint: "Filter direktori dan alasan rekomendasi hanya memakai fasilitas yang sudah terverifikasi.",
    target: "directory-validate-button",
    panel: "directory",
    action: "directory-list",
    demo: "directory-impact",
  },
  {
    id: "assistant",
    eyebrow: "PENCARIAN BANTUAN · 06",
    title: "Tanyakan pada Asisten Akses",
    description: "Tulis kebutuhan dengan bahasa sehari-hari. Asisten menyaring tempat dari data AksesKota, bukan mengarang fasilitas.",
    hint: "Contoh: cari kafe tanpa tangga dekat IPB.",
    target: "assistant",
    panel: null,
    demo: "assistant",
  },
  {
    id: "report",
    eyebrow: "LAPORAN · 07",
    title: "Bantu perbarui kondisi jalan",
    description: "Menu Laporan memiliki dua alur: hambatan sementara dan survei kondisi ruas untuk data aksesibilitas.",
    hint: "Survei ruas membutuhkan akun agar sumber kontribusinya dapat dipertanggungjawabkan.",
    target: "report",
    panel: null,
    demo: "report",
  },
  {
    id: "report-location",
    eyebrow: "MEMBUAT LAPORAN · 08",
    title: "Tentukan lokasi observasi",
    description: "Gunakan GPS atau klik titik pada peta. Backend memasangkan observasi dengan ruas terdekat agar data memiliki konteks jalan.",
    hint: "Lokasi yang akurat membantu beberapa warga menilai ruas yang sama.",
    target: "report-location",
    panel: "report",
    demo: "report-steps",
  },
  {
    id: "community-report-kind",
    eyebrow: "SURVEI KOMUNITAS · 09",
    title: "Pilih Survei ruas jalan",
    description: "Gunakan Laporkan hambatan untuk lubang, banjir, atau jalan tertutup. Gunakan Survei ruas untuk menilai fasilitas dan kualitas jalur.",
    hint: "Panduan ini otomatis membuka formulir Survei ruas jalan.",
    target: "community-report-kind",
    panel: "report",
    action: "road-survey",
    demo: "report-steps",
  },
  {
    id: "road-observation",
    eyebrow: "DATA RUAS · 10",
    title: "Catat yang benar-benar terlihat",
    description: "Nilai ramp, tangga, guiding block, penerangan, tempat duduk, keteduhan, lebar jalur, dan kondisi permukaan. Pilih Tidak tahu jika tidak dapat memastikan.",
    hint: "Jangan menebak. Nilai Tidak tahu lebih aman daripada data fasilitas yang keliru.",
    target: "road-observation",
    panel: "report",
    action: "road-survey",
    demo: "community-fields",
  },
  {
    id: "report-photo",
    eyebrow: "BUKTI LAPORAN · 11",
    title: "Ambil foto yang memperlihatkan ruas",
    description: "Tekan Ambil foto untuk membuka kamera belakang. Foto harus cukup lebar untuk mencocokkan fasilitas, permukaan, dan lokasi observasi.",
    hint: "Hindari wajah dan plat nomor jika tidak diperlukan sebagai bukti.",
    target: "report-photo",
    panel: "report",
    action: "road-survey",
    demo: "camera",
  },
  {
    id: "community-consensus",
    eyebrow: "VERIFIKASI · 12",
    title: "Tiga akun harus menyatakan data sesuai",
    description: "Laporan pertama belum mengubah nilai jalan. Pelapor tidak boleh memverifikasi laporannya sendiri dan setiap akun hanya memiliki satu suara.",
    hint: "Laporan yang diragukan dapat ditandai Perlu cek ulang atau diperiksa moderator.",
    target: "community-consensus",
    panel: "report",
    action: "road-survey",
    demo: "quorum",
  },
  {
    id: "community-impact",
    eyebrow: "DAMPAK DATA · 13",
    title: "Nilai rute berubah setelah konsensus",
    description: "Setelah terverifikasi, backend mengambil median angka dan keputusan mayoritas konservatif. Skor aksesibilitas, kenyamanan, keteduhan, dan alasan rekomendasi dihitung ulang.",
    hint: "Satu laporan ekstrem tidak dapat langsung membuat sebuah ruas dianggap aman atau aksesibel.",
    target: "community-submit",
    panel: "report",
    action: "road-survey",
    demo: "score-impact",
  },
];
