-- MariaDB has spatial POINT/LINESTRING types and the spatial functions used
-- by AksesKota built in, so no extension is required.
--
-- The MVP intentionally leaves geometry nullable because Prisma cannot write
-- Unsupported spatial fields during create; raw SQL fills the geometry right
-- afterward. MariaDB 10.4 requires spatial-indexed columns to be NOT NULL, so
-- indexes are deferred until those writes become single raw INSERT statements.
