"use client";

import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ExternalLink, MapPin, PanelLeftClose, PanelLeftOpen, Phone, Route, Search, ShieldCheck, Star, X } from "lucide-react";
import { apiRequest } from "../../lib/api";
import DestinationMap from "./DestinationMap";
import { DirectoryTransitionBackButton } from "./DirectoryTransitionLink";

const filters=[["WHEELCHAIR_ENTRANCE","Pintu masuk"],["WHEELCHAIR_SEATING","Tempat duduk"],["WHEELCHAIR_RESTROOM","Toilet"],["WHEELCHAIR_PARKING","Parkir"]];

function DestinationDetail({ detail, onClose }) {
  const routeHref=useMemo(()=>`/navigasi?destination=${encodeURIComponent(detail.name)}&externalId=${encodeURIComponent(detail.externalId)}&lng=${detail.longitude}&lat=${detail.latitude}`,[detail]);
  return <aside data-lenis-prevent="true" className="app-scroll-region absolute inset-x-3 bottom-3 z-10 max-h-[72dvh] overflow-y-auto rounded-[20px] bg-white shadow-[0_16px_45px_rgba(20,50,75,.28)] sm:left-auto sm:w-[390px]">
    <div className="relative h-44 bg-[#dff4f0]">{(detail.images?.[0]?.imageUrl||detail.primaryImageUrl)&&<Image unoptimized fill sizes="390px" src={detail.images?.[0]?.imageUrl||detail.primaryImageUrl} alt={`Foto ${detail.name}`} className="object-cover"/>}<button onClick={onClose} aria-label="Tutup detail" className="absolute right-3 top-3 grid size-9 place-items-center rounded-full bg-white/90 shadow"><X className="size-4"/></button><span className="absolute bottom-3 left-3 rounded-full bg-white/90 px-3 py-1.5 text-[8px] font-extrabold text-[#9a3412]">BELUM TERVERIFIKASI KOMUNITAS</span></div>
    <div className="p-5"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><h1 className="text-[18px] font-extrabold leading-6">{detail.name}</h1><p className="mt-1 text-[10px] text-[#667085]">{detail.category||"Tempat"}</p></div><span className="rounded-full bg-[#fff7ed] px-3 py-2 text-[11px] font-extrabold text-[#a34b00]"><Star className="mr-1 inline size-3 fill-current"/>{detail.googleRating??"—"}</span></div>
      <p className="mt-3 text-[10px] leading-5 text-[#667085]">{detail.description||detail.address}</p>
      <div className="mt-4 grid grid-cols-2 gap-2"><Link href={routeHref} className="flex h-11 items-center justify-center gap-2 rounded-xl bg-[#0c6478] text-[10px] font-extrabold text-white"><Route className="size-4"/>Cari rute</Link>{detail.mapsUrl?<a href={detail.mapsUrl} target="_blank" rel="noreferrer" className="flex h-11 items-center justify-center gap-2 rounded-xl border border-[#d0d5dd] text-[10px] font-bold"><ExternalLink className="size-4"/>Sumber Maps</a>:<span/>}</div>
      <h2 className="mt-5 text-[11px] font-extrabold">Informasi aksesibilitas</h2><div className="mt-2 grid grid-cols-2 gap-2">{filters.map(([code,label])=>{const item=detail.accessibilityEvidence.find((row)=>row.featureCode===code);return <div key={code} className={`rounded-xl p-3 ${item?.available===true?"bg-[#effaf8] text-[#0c6478]":item?.available===false?"bg-[#fff1f2] text-[#b42318]":"bg-[#f4f5f6] text-[#667085]"}`}><ShieldCheck className="size-4"/><b className="mt-1 block text-[9px]">{label}</b><small className="text-[8px]">{item?.available===true?"Terindikasi tersedia":item?.available===false?"Terindikasi tidak tersedia":"Belum ada data"}</small></div>})}</div>
      <div className="mt-5 space-y-2 border-t border-[#edf0f2] pt-4"><p className="text-[10px] font-semibold text-[#475467]"><MapPin className="mr-2 inline size-4 text-[#0c6478]"/>{detail.address}</p>{detail.phone&&<a href={`tel:${detail.phone}`} className="block text-[10px] font-semibold text-[#475467]"><Phone className="mr-2 inline size-4 text-[#0c6478]"/>{detail.phone}</a>}{detail.openingHours&&<div className="rounded-xl bg-[#f8fafc] p-3 text-[9px] text-[#475467]"><b>Jam operasional</b>{Object.entries(detail.openingHours).map(([day,hours])=><div key={day} className="mt-1 flex justify-between gap-3"><span>{day}</span><span>{Array.isArray(hours)?hours.join(", "):String(hours)}</span></div>)}</div>}</div>
      <h2 className="mt-5 text-[11px] font-extrabold">Kontribusi komunitas ({detail.communitySummary.postCount})</h2>{detail.posts.length===0?<p className="mt-2 rounded-xl bg-[#fff7ed] p-3 text-[9px] leading-4 text-[#9a3412]">Belum ada warga yang memverifikasi tempat ini. Data sumber hanya menjadi kandidat survei.</p>:<div className="mt-2 space-y-2">{detail.posts.map(post=><article key={post.id} className="rounded-xl border border-[#edf0f2] p-3"><b className="text-[10px]">{post.title}</b><p className="mt-1 text-[9px] text-[#667085]">{post.content}</p></article>)}</div>}
    </div>
  </aside>;
}

export default function DestinationsExplorer() {
  const [query,setQuery]=useState(""); const [activeFilters,setActiveFilters]=useState([]); const [destinations,setDestinations]=useState([]); const [selected,setSelected]=useState(null); const [detail,setDetail]=useState(null); const [status,setStatus]=useState("loading"); const [message,setMessage]=useState(""); const [directoryOpen,setDirectoryOpen]=useState(true);
  const load=useCallback(async()=>{setStatus("loading");try{const params=new URLSearchParams({query,limit:"500"});if(activeFilters.length)params.set("features",activeFilters.join(","));const rows=await apiRequest(`/destinations?${params}`);setDestinations(rows);setMessage(rows.length?`${rows.length} destinasi ditemukan`:"Tidak ada destinasi yang cocok.");setStatus("ready")}catch(error){setMessage(error instanceof Error?error.message:"Destinasi gagal dimuat.");setStatus("error")}},[query,activeFilters]);
  useEffect(()=>{const timer=window.setTimeout(load,250);return()=>window.clearTimeout(timer)},[load]);
  async function choose(item){setSelected(item);setDetail(null);try{setDetail(await apiRequest(`/destinations/${encodeURIComponent(item.externalId)}`))}catch(error){setMessage(error instanceof Error?error.message:"Detail gagal dimuat.")}}
  function toggle(value){setActiveFilters(current=>current.includes(value)?current.filter(item=>item!==value):[...current,value])}
  return <main className="directory-page-enter flex h-dvh min-h-[620px] flex-col overflow-hidden bg-[#eef3f4]"><header className="z-30 flex h-16 shrink-0 items-center gap-3 border-b border-[#dfe7e8] bg-white px-4 shadow-sm sm:px-6"><DirectoryTransitionBackButton className="grid size-10 place-items-center rounded-full bg-[#effaf8] text-[#0c6478]"/><div><b className="text-[16px] text-[#173c61]">AksesKota</b><p className="text-[9px] font-bold uppercase tracking-[.16em] text-[#12a594]">Destinasi Bogor</p></div><button type="button" onClick={()=>setDirectoryOpen(value=>!value)} aria-expanded={directoryOpen} aria-controls="destination-directory-panel" className="ml-auto flex h-10 items-center gap-2 rounded-full border border-[#d8e4e5] bg-white px-3 text-[9px] font-extrabold text-[#0c6478] shadow-sm transition hover:-translate-y-0.5 hover:bg-[#effaf8] sm:px-4">{directoryOpen?<PanelLeftClose className="size-4"/>:<PanelLeftOpen className="size-4"/>}<span className="hidden sm:inline">{directoryOpen?"Lihat peta penuh":"Buka direktori"}</span></button><div className="hidden rounded-full bg-[#fff7ed] px-3 py-2 text-[9px] font-bold text-[#9a3412] xl:block">Data sumber belum menggantikan survei komunitas</div></header>
    <div className="destinations-layout relative min-h-0 flex-1 overflow-hidden" style={{"--directory-sidebar":directoryOpen?"390px":"0px"}}><section id="destination-directory-panel" aria-hidden={!directoryOpen} className={`absolute inset-0 z-20 flex min-h-0 flex-col border-r border-[#dfe7e8] bg-white shadow-[12px_0_34px_rgba(24,46,58,.12)] transition duration-500 ease-[cubic-bezier(.22,1,.36,1)] lg:relative lg:z-10 lg:shadow-none ${directoryOpen?"translate-x-0 opacity-100":"pointer-events-none -translate-x-full opacity-0"}`}><div className="border-b border-[#edf0f2] p-4"><label className="flex h-12 items-center gap-3 rounded-[15px] bg-[#f3f6f7] px-4"><Search className="size-4 text-[#0c6478]"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Cari restoran, mall, taman..." className="min-w-0 flex-1 bg-transparent text-[11px] font-semibold outline-none"/>{query&&<button onClick={()=>setQuery("")} aria-label="Hapus pencarian"><X className="size-4"/></button>}</label><div className="directory-chip-scroll mt-3 flex gap-2 overflow-x-auto pb-1">{filters.map(([value,label])=><button key={value} onClick={()=>toggle(value)} className={`shrink-0 rounded-full border px-3 py-2 text-[9px] font-bold ${activeFilters.includes(value)?"border-[#0c6478] bg-[#0c6478] text-white":"border-[#dfe7e8] bg-white text-[#475467]"}`}>{label}</button>)}</div><p className="mt-3 text-[9px] font-semibold text-[#667085]">{status==="loading"?"Memuat destinasi...":message}</p></div>
      <div data-lenis-prevent="true" className="app-scroll-region flex-1 space-y-3 overflow-y-auto p-3">{status==="loading"&&[1,2,3].map(item=><div key={item} className="h-28 animate-pulse rounded-[16px] bg-[#eef2f3]"/>)}{destinations.map(item=><button key={item.externalId} onClick={()=>choose(item)} className={`flex w-full gap-3 rounded-[17px] border-2 p-3 text-left ${selected?.externalId===item.externalId?"border-[#35cbb0] bg-[#effaf8]":"border-[#edf0f2] bg-white"}`}>{item.primaryImageUrl?<Image unoptimized src={item.primaryImageUrl} alt={`Foto ${item.name}`} width={84} height={84} className="size-20 shrink-0 rounded-[13px] object-cover"/>:<span className="grid size-20 shrink-0 place-items-center rounded-[13px] bg-[#e7f6f3] text-[#0c6478]"><MapPin className="size-6"/></span>}<span className="min-w-0 flex-1"><b className="block line-clamp-2 text-[11px] leading-4">{item.name}</b><small className="mt-1 block text-[9px] text-[#667085]">{item.category||"Tempat"}</small><span className="mt-2 flex items-center gap-2 text-[9px]"><b className="text-[#a34b00]"><Star className="mr-1 inline size-3 fill-[#f59e0b] text-[#f59e0b]"/>{item.googleRating??"—"}</b><span className="text-[#98a2b3]">{item.googleReviewCount?.toLocaleString("id-ID")||0} ulasan</span></span><span className="mt-2 inline-block rounded-full bg-[#effaf8] px-2 py-1 text-[8px] font-bold text-[#0c6478]">{item.knownFeatureCount} data akses</span></span></button>)}</div></section>
      <section className="relative h-full min-h-0 overflow-hidden"><DestinationMap destinations={destinations} selectedId={selected?.externalId} onSelect={choose}/>{selected&&!detail&&<div className="absolute bottom-3 right-3 h-72 w-[min(390px,calc(100%-24px))] animate-pulse rounded-[20px] bg-[#eef2f3] shadow-xl"/>}{detail&&<DestinationDetail detail={detail} onClose={()=>{setSelected(null);setDetail(null)}}/>}</section></div></main>;
}
