export const directoryGuideSteps = [
  {
    title: "Jelajahi Direktori Bogor",
    eyebrow: "PANDUAN DIREKTORI",
    description: "Pelajari cara membuka daftar tempat, melihat peta penuh, mencari fasilitas, dan menutup detail tempat.",
    hint: "Panduan dapat dibuka ulang dari tombol tanda tanya di header.",
    target: null,
    setup: "open-panel",
  },
  {
    title: "Panel daftar dapat ditutup",
    eyebrow: "TAMPILAN · 01",
    description: "Tekan tombol ini saat ingin memperluas peta. Data dan filter yang sudah dipilih tidak akan hilang.",
    hint: "Pada ponsel, menutup panel membuat area peta lebih mudah dilihat.",
    target: "directory-toggle",
    setup: "open-panel",
  },
  {
    title: "Peta penuh untuk melihat sebaran",
    eyebrow: "TAMPILAN · 02",
    description: "Ketika panel ditutup, marker tempat terlihat lebih luas. Tekan tombol yang sama untuk membuka daftar kembali.",
    hint: "Marker dapat dipilih langsung dari peta.",
    target: "directory-toggle",
    setup: "close-panel",
  },
  {
    title: "Cari tempat berdasarkan nama",
    eyebrow: "PENCARIAN · 03",
    description: "Ketik restoran, mal, taman, atau nama tempat. Hasil akan diperbarui tanpa perlu memuat ulang halaman.",
    hint: "Hapus isi kolom untuk kembali melihat semua tempat.",
    target: "directory-search",
    setup: "open-panel",
  },
  {
    title: "Saring fasilitas yang dibutuhkan",
    eyebrow: "FILTER · 04",
    description: "Gunakan filter pintu masuk, tempat duduk, toilet, atau parkir. Beberapa filter dapat dipilih sekaligus.",
    hint: "Filter didasarkan pada data akses yang tersedia, bukan asumsi.",
    target: "directory-filters",
    setup: "open-panel",
  },
  {
    title: "Pilih kartu untuk membuka detail",
    eyebrow: "DETAIL TEMPAT · 05",
    description: "Kartu menampilkan foto, rating, jumlah ulasan, dan jumlah data akses sebelum kamu membuka informasi lengkap.",
    hint: "Panduan akan membuka contoh tempat pada langkah berikutnya.",
    target: "directory-place-card",
    setup: "open-panel",
  },
  {
    title: "Baca detail dan bukti akses",
    eyebrow: "DETAIL TEMPAT · 06",
    description: "Di sini tersedia alamat, jam buka, fasilitas aksesibilitas, serta tombol untuk menjadikan tempat sebagai tujuan.",
    hint: "Gulir panel detail untuk melihat seluruh informasi.",
    target: "directory-detail",
    setup: "open-place",
  },
  {
    title: "Tutup detail sebelum mencari lagi",
    eyebrow: "KEMBALI MENCARI · 07",
    description: "Tekan tombol silang ini untuk menutup tempat yang sedang dibuka. Panel daftar akan muncul kembali agar kamu bisa mencari tempat lain.",
    hint: "Menutup detail tidak menghapus filter pencarianmu.",
    target: "directory-detail-close",
    setup: "keep-place",
  },
];
